Repository ploidddddd/purplekeep, pull requests merged in 2018-02, with the labels that each got.

#43 Added sort by Location
  application/controllers/event/CEvent.php
  application/models/user/MEvent.php
  application/views/vLandingPage.php
Labels: Development/Module Done, Pending

#84 Fixed redirection to login page after registering.
  application/controllers/user/CUser.php
  application/views/vRegistrationConfirmation.php
Labels: bug

#120 SPRINT 8 : bug fix
  application/controllers/event/CEvent.php
  application/models/MTicket.php
  application/views/calendar/vCalendar.php
  application/views/vEventDetails.php
  application/views/vEventDetailsFromCalendar.php
  application/views/vEventDetailsOrg.php
  application/views/vEvents.php
  application/views/vNewEvent.php
Labels: Pending
