Repository ploidddddd/purplekeep, pull requests merged in 2018-03, with the labels that each got.

#159 Sprint 8: Kyle & Entoma (Fixed) Added Title/Header for announcements
  application/controllers/admin/CAdmin.php
  application/views/admin/vAnnouncements.php
  application/views/user/vAnnouncementPage.php
Labels: Development/Module Done, Pending, enhancement

#162 Adjustments of dimensions of the event container and for the landing …
  application/controllers/event/CEvent.php
  application/views/vEvents.php
  application/views/vLandingPage.php
  application/views/vNewEvent.php
  assets/nikkiAssets/css/responsive.css
  assets/nikkiAssets/css/style.css
Labels: enhancement

#267 Added functionality in vCart when you select certain ticket, total wi…
  application/views/vCart.php
Labels: Development/Module Done, bug, enhancement

#282 Final Sprint: Fix for birthday in registration. This will now count including the month
  application/views/vSignUp.php
Labels: Development/Module Done, Pending

#304 Added required field symbol for Signup fields and New Event fields to…
  application/views/vNewEvent.php
  application/views/vSignUp.php
  assets/configurations 0/Strings0.php
  assets/configurations 1/Strings1.php
Labels: Development/Module Done

#302 FINAL SPRINT: Fix for update Profile Birthday to check month "You are below 18"
  application/views/vEvents.php
Labels: Development/Module Done, Pending, bug

#305 push-to-dev request para sa katong required fields.
  application/views/vNewEvent.php
  application/views/vSignUp.php
  assets/configurations 0/Strings0.php
  assets/configurations 1/Strings1.php
Labels: Development/Module Done
